[project]
name = "backend-first"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Serhii", email = "sersem0305@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
backend-first = "backend_first:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
